<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32mg21.modem" label="MODEM" name="MODEM" description="" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="MODEM.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="MODEM.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="MODEM.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="MODEM.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="MODEM.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
    </properties>
    <propertyCategories>
      <category label="MODEM">
        <subCategory label="">
          <propertyRef refId="MODEM.usedbysdk.BOOL"/>
          <propertyRef refId="MODEM.hiddenbysdk.BOOL"/>
          <propertyRef refId="MODEM.showadvanced.BOOL"/>
          <propertyRef refId="MODEM.forceenable.BOOL"/>
          <propertyRef refId="MODEM.owner.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
