/***************************************************************************//**
 * @brief Set of APIs for the main plugin.
 *******************************************************************************
 * # License
 * <b>Copyright 2018 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * The licensor of this software is Silicon Laboratories Inc. Your use of this
 * software is governed by the terms of Silicon Labs Master Software License
 * Agreement (MSLA) available at
 * www.silabs.com/about-us/legal/master-software-license-agreement. This
 * software is distributed to you in Source Code format and is governed by the
 * sections of the MSLA applicable to Source Code.
 *
 ******************************************************************************/

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"

#include "hal/hal.h"
#include "flex-bookkeeping.h"
#include "flex-callbacks.h"

#if defined(EMBER_AF_PLUGIN_MICRIUM_RTOS)
#include EMBER_AF_API_MICRIUM_RTOS
#endif

// Our entry point is typically main(), except in simulation.
// In simulation we don't include the cortexm3-specific headers.
#if defined(EMBER_TEST)
  #define MAIN nodeMain
  #if defined(EMBER_AF_API_DIAGNOSTIC_CORTEXM3)
    #undef EMBER_AF_API_DIAGNOSTIC_CORTEXM3
  #endif // EMBER_AF_API_DIAGNOSTIC_CORTEXM3
#else
  #define MAIN main
#endif // EMBER_TEST

// If serial functionality is enabled, we will initialize the serial ports
// during startup.  This has to happen after the HAL and gateway, if applicable,
// are initialized.
#ifdef EMBER_AF_API_SERIAL
  #include EMBER_AF_API_SERIAL
// TODO: SERIAL_INIT() should be auto-generated by AppBuilder
  #define SERIAL_INIT()                                                                                \
  do {                                                                                                 \
    emberSerialInit((uint8_t)APP_SERIAL, (SerialBaudRate)APP_BAUD_RATE, (SerialParity)PARITY_NONE, 1); \
  } while (false)
#else
  #define SERIAL_INIT()
  #define emberSerialPrintfLine(...)
#endif

// If printing is enabled, we will print some diagnostic information about the
// most recent reset and also during runtime.  On some platforms, extended
// diagnostic information is available.
#if defined(EMBER_AF_API_SERIAL) && defined(EMBER_AF_PRINT_ENABLE)
  #if defined(EMBER_AF_API_DIAGNOSTIC_CORTEXM3)
    #include EMBER_AF_API_DIAGNOSTIC_CORTEXM3
  #endif
static void printResetInformation(void);
  #define PRINT_RESET_INFORMATION printResetInformation
  #define emberAfGuaranteedPrint(...) \
  emberSerialGuaranteedPrintf(APP_SERIAL, __VA_ARGS__)
  #define emberAfGuaranteedPrintln(...)                   \
  do {                                                    \
    emberSerialGuaranteedPrintf(APP_SERIAL, __VA_ARGS__); \
    emberSerialGuaranteedPrintf(APP_SERIAL, "\r\n");      \
  } while (false)
#else
  #define PRINT_RESET_INFORMATION()
  #define emberAfGuaranteedPrint(...)
  #define emberAfGuaranteedPrintln(...)
#endif

EmberTaskId emAppTask;
extern const EmberEventData emAppEvents[];

int MAIN(MAIN_FUNCTION_PARAMETERS)
{
  halInit();

  INTERRUPTS_ON();

  SERIAL_INIT();

  PRINT_RESET_INFORMATION();

#if defined(EMBER_AF_PLUGIN_FREE_RTOS)
  extern void emberPluginRtosInitAndRunConnectTask(void);
  emberPluginRtosInitAndRunConnectTask();
#elif defined(EMBER_AF_PLUGIN_MICRIUM_RTOS)
  emberAfPluginMicriumRtosInitAndRunTasks();
#else
  EmberStatus status;

  emberTaskEnableIdling(true);

  emAppTask = emberTaskInit(emAppEvents);

  // Initialize the radio and the stack.  If this fails, we have to assert
  // because something is wrong.
  status = emberInit();
  emberSerialPrintfLine(APP_SERIAL, "Init: 0x%x", status);
  assert(status == EMBER_SUCCESS);

  emberAfInit();
  emberAfMainInitCallback();

  while (true) {
    halResetWatchdog();

    // Let the stack or EZSP layer run periodic tasks.
    emberTick();

    // Let the application and plugins run periodic tasks.
    emberAfMainTickCallback();
    emberAfTick();

    emberRunTask(emAppTask);
  }
#endif

  return 0;
}

//------------------------------------------------------------------------------
// Static functions.

#ifdef EMBER_AF_PRINT_ENABLE

static void printResetInformation(void)
{
  // Information about the most recent reset is printed during startup to aid
  // in debugging.
  emberAfGuaranteedPrintln("Reset info: 0x%x (%p)",
                           halGetResetInfo(),
                           halGetResetString());

#if defined(EMBER_AF_API_DIAGNOSTIC_CORTEXM3)
  emberAfGuaranteedPrintln("Extended reset info: 0x%2x (%p)",
                           halGetExtendedResetInfo(),
                           halGetExtendedResetString());
  if (halResetWasCrash()) {
    halPrintCrashSummary(APP_SERIAL);
    halPrintCrashDetails(APP_SERIAL);
    halPrintCrashData(APP_SERIAL);
  }
#endif // EMBER_AF_API_DIAGNOSTIC_CORTEXM3
}

#endif // EMBER_AF_PRINT_ENABLE
